### ISSUE TITLE
update versions in your pubspec

### ISSUE THREAD

**Issue by sgehrman** [natintosh/intl-phone-number-input#13]
I have this in my pubspec:
  provider: ^4.0.1

If I add intl_phone_number_input, I get this:

No other packages seem to have these kinds of problems.  I'm fairy new to Flutter, so I'm not sure the best answer.

Because intl_phone_number_input 0.2.0 depends on provider ^3.2.0 and no versions of intl_phone_number_input match >0.2.0 <0.3.0, intl_phone_number_input ^0.2.0 requires provider ^3.2.0.
So, because therapist_training depends on both provider ^4.0.1 and intl_phone_number_input ^0.2.0, version solving failed.

pub get failed (1; So, because therapist_training depends on both provider ^4.0.1 and intl_phone_number_input ^0.2.0, version solving failed.)
exit code 1

**Comment by natintosh** [comment]
Hello @sgehrman thanks bring this to my attention. I will work on a fix

**Comment by natintosh** [comment]
I have upgraded the provider dependency and updated the example. I'll be closing this now thanks and please reach of if any help or have any suggestion

**Comment by sgehrman** [comment]
great, I woke up this morning and saw the new version.  Thanks for the quick update!
