### ISSUE TITLE
Make validation optional

### ISSUE THREAD

**Issue by zakton5** [natintosh/intl-phone-number-input#15]
Hi! Great job on this so far!

Would it be possible to add an `isRequired` field or something like that? I have a form where I do not require a phone number but it is there if the user wants to put one in. Maybe there is already a way to accomplish this but I couldn't figure it out.

**Comment by natintosh** [comment]
Hi, @zakton5 thanks for your feedback. I am going to add new property called `ignore Blank`.  If set to true this would not validate the field.

**Comment by natintosh** [comment]
Hi @zakton5 

The feature requested has been added on PR #18. Thanks for your contribution, I'll be closing this issue
