### ISSUE TITLE
Feature requests - Updated

### ISSUE THREAD

**Issue by guyzk** [natintosh/intl-phone-number-input#16]
- Other than initial ISO which is already implemented it would be nice to have the option to restrict to one country (select box disabled and set to the requested country code) while still having the phone number validation.

- Have the option to restrict to specific phone types (mobile, land line, etc).

- RTL layout support (Mainly the fact that the phone number cannot be RTL event though the entire layout is RTL the phone number itself (and the phone country code) should be in LTR
e.g. currently in RTL the country code is 1+ instead of +1

- When using InternationalPhoneNumberInput.withCustomDecoration you cannot change the error text manually and the is no errorMessage in the constructor. Please allow to modify the error message in this factory as well

- Will it be possible to add the country names to the select box and maybe event provide a list of translations by the iso2 code?

- Add a search input to easily select a country instead of scrolling through the whole list.

Thanks!

**Comment by guyzk** [comment]
> Other than initial ISO which is already implemented it would be nice to have the option to restrict to one country (select box disabled and set to the requested country code) while still having the phone number validation.

My Bad - Can be done with custom country list

> RTL layout support (Mainly the fact that the phone number cannot be RTL event though the entire layout is RTL the phone number itself (and the phone country code) should be in LTR
e.g. currently in RTL the country code is 1+ instead of +1

Can be fixed by adding "textDirection: TextDirection.ltr" to the following lines in widget file:
Row 293: In the Row widget
Row 313: In the TextFormFieldWidget
Row 379: In the select item Row widget
Row 390: In the select item Text widget 
Tested: This forces the widget to align correctly even for RTL languages

**Comment by guyzk** [comment]
@natintosh I can issue a pull request for most of these features and more.
Do you prefer a pull request for each feature or one for all of them?

**Comment by natintosh** [comment]
Sure 🤗

**Comment by guyzk** [comment]
Done https://github.com/natintosh/intl-phone-number-input/pull/17
Regarding the translations I might be able to add 2 languages as a start
The rest can be done as pull requests from the community
Happy to help

**Comment by natintosh** [comment]
Hi @guyzk  thanks for your contributions then I added the draggable scrollable sheet to the modal
