### ISSUE TITLE
Country flag and code alignment gone

### ISSUE THREAD

**Issue by jefferyleo** [natintosh/intl-phone-number-input#25]
The country code and flag alignment gone if I specific only 1 country to show out at the moment.

```
InternationalPhoneNumberInput(
              onInputChanged: (PhoneNumber number) {
                print(number.phoneNumber);
              },
              isEnabled: true,
              autoValidate: true,
              formatInput: true,
              countries: ['MY'],
            ),
```
![Screenshot_20200330-200321](https://user-images.githubusercontent.com/6831609/77910449-b5a58680-72c1-11ea-9326-4073acf8f1e6.jpg)

If there's more than 1 country in array, then it working fine.

**Comment by natintosh** [comment]
Hi @jefferyleo  PR #29 fixed this issue, I'll be closing this. Thanks for your contribution.
