### ISSUE TITLE
When controller is specified, don't call dispose().

### ISSUE THREAD

**Issue by bscottsmith** [natintosh/intl-phone-number-input#26]
When a text controller is specified, it is the callers responsibility to dispose of it at the proper time. Do not call dispose() on the supplied controller. Otherwise the following error may occur:

> Unhandled Exception: A InputProvider was used after being disposed.
> Once you have called dispose() on a InputProvider, it can no longer be used.

This was introduced by the implementation of issue #3

**Comment by natintosh** [comment]
Hi, @bscottsmith  thanks for your feedback I just pushed a fixed for this issue. I'll be closing this now.
