### ISSUE TITLE
Add Key values for input fields for testing

### ISSUE THREAD

**Issue by bscottsmith** [natintosh/intl-phone-number-input#27]
Add key values for input fields (ie: "countrySelector" and "phoneInput"), as well as keys for items in the country code list, so that tests can be written to select country codes and input phone numbers. For example:

> await driver.tap(find.byValueKey('countrySelector'));
> await driver.tap(find.byValueKey('country_US'));
> await driver.tap(find.byValueKey('phoneInput'));
> await driver.enterText("5555551234");

**Comment by natintosh** [comment]
Hi @bscottsmith, thanks for the recommendation. I had to go and read up on testing in Flutter, it took a while, I just add support for integration testing, you can check out an example [here](https://gist.github.com/natintosh/b7b40d75240a65fdb63942a4b36753e5).
