### ISSUE TITLE
Can set initial value in input field

### ISSUE THREAD

**Issue by shrutikateiosys** [natintosh/intl-phone-number-input#3]
I want to edit mobile number which comes with country code but there is no option like controller or no intial value input provided how can i use this input type when i want to edit field. kindly help.

**Comment by natintosh** [comment]
Hi👋 @shrutikateiosys, so sorry for the late response I have been very busy with work I just added TextEditingController to the constructor with which enables you to set text . CHEERS!!! 🎉🎉🎉🎇🎇🎇
