### ISSUE TITLE
Use of Textfield autofocus 

### ISSUE THREAD

**Issue by Shiftane** [natintosh/intl-phone-number-input#30]
Hi,
Is that possible to use the text field autofocus in the constructor ?
Thanks for the answer

**Comment by natintosh** [comment]
Hi @Shiftane, The TextField autofocus feature is not yet available.

**Comment by Shiftane** [comment]
Can add it if I can do a PR


Le 13 avril 2020 à 10:17:38, Ogunye Nathaniel Oluwatobiloba (
notifications@github.com) a écrit:

Hi @Shiftane <https://github.com/Shiftane>, The TextField autofocus feature
is not yet available.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/natintosh/intl-phone-number-input/issues/30#issuecomment-612802411>,
or unsubscribe

**Comment by natintosh** [comment]
Sure that will be great

**Comment by natintosh** [comment]
I just added the feature thanks. I'll close this now
