### ISSUE TITLE
Submitting the form without typing anything

### ISSUE THREAD

**Issue by catside295** [natintosh/intl-phone-number-input#31]
I'm using your package in a single field form with autovalidate=false and ignoreBlank=false. I managed to get auto focus when the user comes to the page. But I'm facing an issue if the user submit the form without typing any key. In that case, the validator of the TextFormField seems to be not called as well as _phoneNumberControllerListener. So in the RaisedButton.onPress() method, formKey.currentState.validate()=true and the form is successfully submitted. I'm aware that this use case can be valid. But in my case, the user has to fill the phone number field. So I would like to raise an error if the user submit the form without entering a single character.

I think that it can be achieved by exposing the value of provider.isNotValid = false; in the method _phoneNumberControllerListener. Or it could be something like this provider.isNotValid=! ignoreBlank.

Do you think that my request is doable?

**Comment by natintosh** [comment]
Hi, @catside295 thanks for raising this issue I checked it up and found out it wasn't behaving as expected. The form doesn't validate if it's empty when ignoreBlank is set to false. I'll try to work on a fix now

**Comment by natintosh** [comment]
I just pushed a fix, thanks for the contribution
