### ISSUE TITLE
Add images or gifs in readme to show the looks of the input field

### ISSUE THREAD

**Issue by piyushchauhan** [natintosh/intl-phone-number-input#33]
Pls add images or gif in readme to show the output of the input field. 
It will be better for developers to understand it and quickly use it.
Reference can be taken from here. https://api.flutter.dev/flutter/material/SliverAppBar-class.html

**Comment by natintosh** [comment]
Hello @piyushchauhan  thanks for the suggestion, I just updated the readme.
