### ISSUE TITLE
Invalid phone number

### ISSUE THREAD

**Issue by illiashvedov** [natintosh/intl-phone-number-input#36]
I initially made my home country by default, after which, based on the number I received, I change the country, but as soon as I put my number in there, I get an error that the format is wrong

```
PhoneNumber _initialPhoneNumber = PhoneNumber(isoCode: 'US');

  @override
  void initState() {
    if (widget.phoneNumber != null) {
      _parsablePhoneNumber(widget.phoneNumber);
    }

    super.initState();
  }

  Future _parsablePhoneNumber(String phoneNumber) async {
    if (phoneNumber.isNotEmpty) {
      PhoneNumber numberRegionInfo =
          await PhoneNumber.getRegionInfoFromPhoneNumber(phoneNumber);

      setState(() {
        _initialPhoneNumber = numberRegionInfo;
      });
    }
  }
```

Auto-validation is enabled in your widget

**Comment by natintosh** [comment]
@illiashvedov  I recreated this at my end at it works could you shed more light on  this matter

**Comment by illiashvedov** [comment]
If you set the default country this way, then I can’t enter anything into the number line, but if the phone number was given to me, then it always displays as the wrong number, although if you select the text field and then cancel it, the check says that the number is valid.

**Comment by natintosh** [comment]
If I get this right, I believe what you are trying to say is that anytime you set a new state for the initial value with a valid phone number you get a validation error, right?

**Comment by illiashvedov** [comment]
Yes

**Comment by natintosh** [comment]
I just pushed a fix Thanks 👍.

**Comment by yusuf-umar** [comment]
hi, bellow is my code but i keep getting invalid phone number. when i input the correct phone number

 InternationalPhoneNumberInput(
                          onInputChanged: (PhoneNumber number) {
                            // print(number.phoneNumber);
                          },
                          onInputValidated: (bool value) {
                            print(value);
                          },
                          selectorConfig: SelectorConfig(
                            selectorType: PhoneInputSelectorType.DIALOG,
                          ),
                          ignoreBlank: false,
                          autoValidateMode: AutovalidateMode.disabled,
                          selectorTextStyle: TextStyle(color: Colors.black),
                          initialValue: number,
                          textFieldController: controller,
                          formatInput: true,
                          keyboardType: TextInputType.numberWithOptions(
                              signed: true, decimal: true),
                          inputBorder: InputBorder.none,
                          // border: InputBorder.none,
                          onSaved: (PhoneNumber number) {
                            print('On Saved: $number');
                          },
                        ),

**Comment by kehindemary** [comment]
I get the same error

**Comment by yusuf-umar** [comment]
> I get the same error

hi, i was able to solved error by adding a validator, to the widget.
... sample
   borderRadius: BorderRadius.circular(5)),
                        child: InternationalPhoneNumberInput(
                          validator: _phoneValidator, // add this line. then declare you _phoneValidator function somewhere
                          onInputChanged: (PhoneNumber number) {
                            // print(number.phoneNumber);
                          },

.....


.......   

  String? _phoneValidator(value) {
    if (value!.length < 6) {
      return "Please enter correct phone number";
    } else {
      return null;
    }
  }

**Comment by kehindemary** [comment]
Thank you Yusuf, I tried it still got the red textfield 
<img width="348" alt="err" src="https://user-images.githubusercontent.com/43091086/147688898-30745085-a4b3-4da0-817b-97eaed395619.PNG">

**Comment by anuroopmallick9** [comment]
Hi, In my case I have provided TWO IntlPhoneField in a form, however, one of them is not mandatory. Therefore, whenever I try to send an empty field I get the error message as "Invalid mobile number". How do I fix this issue?
