### ISSUE TITLE
Listening to onSubmitted 

### ISSUE THREAD

**Issue by royibernthal** [natintosh/intl-phone-number-input#4]
I'd like to listen to onSubmitted which is invoked by the native keyboard.

Could you please add that listener to the API and pass it to the TextField component you're wrapping? It should be pretty straightforward.

If you could go one step further and make it compatible with flutter's Form it'd be even better, after all, this component is likely to be used as part of a form.

**Comment by natintosh** [comment]
Hi @royibernthal thanks for your feedback I have updated and publish the update

**Comment by royibernthal** [comment]
Thanks :) Any idea when it'll be published to pub.dev as well? I still see the old version there.

https://pub.dev/packages/intl_phone_number_input#-installing-tab-
