### ISSUE TITLE
The getter 'countryCode' was called on null

### ISSUE THREAD

**Issue by royibernthal** [natintosh/intl-phone-number-input#5]
It happens to me inconsistently on the first build of the widget. You might wanna check if _selectedCountry exists.

![countryCode](https://user-images.githubusercontent.com/7274413/67638356-467bce80-f8ec-11e9-84aa-1500eb1326f3.png)

**Comment by natintosh** [comment]
Hi @royibernthal thanks for bringing this up I haven't still figure out the cause of this bug could you please recreate the steps that caused this error. Thanks.
