### ISSUE TITLE
Need an initial phone number for secure storage

### ISSUE THREAD

**Issue by dungnv2602** [natintosh/intl-phone-number-input#6]
I stored a valid phone number in secure storage and want to get it as an initial value when a user reopen the page. I can't find anywhere to put this value in this widget.

**Comment by natintosh** [comment]
On the latest version of the package you can now pass a TextEditingController as a parameter.

To set/change the value of the textField you could always do 

```
setState(){
 _yourControllerReference.text = 'what ever value you want set'
}
```

```
InternationalPhoneNumberInput({
    Key key,
    @required this.onInputChanged,
    this.onInputValidated,
    this.focusNode,
    **this.textFieldController,**
    this.onSubmit,
    this.keyboardAction,
    this.countries,
    this.inputBorder,
    this.inputDecoration,
    this.initialCountry2LetterCode = 'NG',
    this.hintText = '(800) 000-0001 23',
    this.shouldParse = true,
    this.shouldValidate = true,
    this.formatInput = true,
    this.errorMessage = 'Invalid phone number',
  })
```

I hope this help

**Comment by dungnv2602** [comment]
> On the latest version of the package you can now pass a TextEditingController as a parameter.
> 
> To set/change the value of the textField you could always do
> 
> ```
> setState(){
>  _yourControllerReference.text = 'what ever value you want set'
> }
> ```
> 
> Don't Forget to set your controller reference on the highlighted argument
> 
> ```
> InternationalPhoneNumberInput({
>     Key key,
>     @required this.onInputChanged,
>     this.onInputValidated,
>     this.focusNode,
>     **this.textFieldController,**
>     this.onSubmit,
>     this.keyboardAction,
>     this.countries,
>     this.inputBorder,
>     this.inputDecoration,
>     this.initialCountry2LetterCode = 'NG',
>     this.hintText = '(800) 000-0001 23',
>     this.shouldParse = true,
>     this.shouldValidate = true,
>     this.formatInput = true,
>     this.errorMessage = 'Invalid phone number',
>   })
> ```
> 
> I hope this help

Yeah I know that, but the thing is when you doing that the format of phone number in text field is broken

**Comment by natintosh** [comment]
Oh that's true I'll work on that for the next update. Big thanks 👊

**Comment by dungnv2602** [comment]
Thank you.

**Comment by natintosh** [comment]
Hi @dungnv2602 I've just made changes and push the update. You can now upgrade your dart package
