### ISSUE TITLE
disabled state and formating issues

### ISSUE THREAD

**Issue by eboye** [natintosh/intl-phone-number-input#9]
Can you add an option enabled like on TextFormField widget to be able to toggle the enabled state?

I'm using the AbsorbPointer widget to wrap the field to disable user input, but it's a hack.

Also it would be nice if we could disable or change the formatting. For example (XXX) XX XXX is not a proper format for Serbian phone numbers, but (XX) XXX XXX.

Also when the initial value is passed, it gives me:

+381 +381XXXXXXXX
instead of
+381 (XXX)XXXXX

btw, nice plugin :)

**Comment by natintosh** [comment]
Hi @eboye, I'm currently working on the custom formatting for phone number you can find it [here](https://gist.github.com/natintosh/716d36674e59cbf18e1d69e790b1221d)

**Comment by natintosh** [comment]
> Hi @eboye, I'm currently working on the custom formatting for phone number you can find it [here](https://gist.github.com/natintosh/716d36674e59cbf18e1d69e790b1221d)

It works it but there's a blockage that is if you update the test it will clearing the text with the keyboard backspace would cause issue

**Comment by natintosh** [comment]
So the idea there is that I'll use your hint text has the mask

**Comment by eboye** [comment]
OK, that works for me. Better no formatting than wrong formatting :)

**Comment by amadeu01** [comment]
@natintosh how can we disable the current mask?

**Comment by natintosh** [comment]
@amadeu01  Right now package is not supporting the disabling of the current mask, It was something I missed I will without doubt add this by the next update. Thanks

**Comment by natintosh** [comment]
Hi @eboye  I've publish a new version of the package that has a new feature call formatAsYouType and add diable state. Thanks 👊

**Comment by eboye** [comment]
Great, thanks 👊
